package com.bloodbond.alertsystem.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * LifePulse - Emergency Blood Alert System
 * Entity: Alert
 * Maps to the 'alerts' table in the MySQL database.
 * Represents an urgent broadcast initiated by a patient, physician, or hospital attendant.
 */
@Entity
@Table(name = "alerts")
public class Alert {

    // Primary Key with auto-incrementing ID generated by MySQL (IDENTITY strategy)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Full name of the patient requiring blood
    @Column(name = "patient_name", nullable = false, length = 100)
    private String patientName;

    // Required blood group: A+, A-, B+, B-, AB+, AB-, O+, O-
    @Column(name = "blood_group", nullable = false, length = 5)
    private String bloodGroup;

    // Hospital name, ward number, or location description
    @Column(name = "location", nullable = false, length = 255)
    private String location;

    // Direct phone number of the emergency contact / hospital desk
    @Column(name = "contact_number", nullable = false, length = 20)
    private String contactNumber;

    // Detailed clinical emergency note (e.g. trauma, surgery, platelet requirement)
    @Column(name = "message", nullable = false, columnDefinition = "TEXT")
    private String message;

    // Current status of the alert: ACTIVE, FULFILLED, CANCELLED
    @Column(name = "status", length = 20)
    private String status;

    // Timestamp when the alert was triggered (updatable = false protects audit history)
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Default No-Args Constructor
     * Mandatory for Hibernate JPA to instantiate entity objects via reflection.
     */
    public Alert() {
    }

    /**
     * Parameterized Constructor for creating new Alert instances
     */
    public Alert(String patientName, String bloodGroup, String location, String contactNumber, String message) {
        this.patientName = patientName;
        this.bloodGroup = bloodGroup;
        this.location = location;
        this.contactNumber = contactNumber;
        this.message = message;
        this.status = "ACTIVE";
    }

    /**
     * JPA Lifecycle Callback:
     * Automatically executes right before this entity is first inserted into the database.
     */
    @PrePersist
    protected void onCreate() {
        if (this.createdAt == null) {
            this.createdAt = LocalDateTime.now();
        }
        if (this.status == null || this.status.trim().isEmpty()) {
            this.status = "ACTIVE";
        }
    }

    // =========================================================================
    // Getters and Setters
    // Allows controlled access and mutation of private fields
    // =========================================================================

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPatientName() {
        return patientName;
    }

    public void setPatientName(String patientName) {
        this.patientName = patientName;
    }

    public String getBloodGroup() {
        return bloodGroup;
    }

    public void setBloodGroup(String bloodGroup) {
        this.bloodGroup = bloodGroup;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getContactNumber() {
        return contactNumber;
    }

    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        return "Alert{" +
                "id=" + id +
                ", patientName='" + patientName + '\'' +
                ", bloodGroup='" + bloodGroup + '\'' +
                ", location='" + location + '\'' +
                ", contactNumber='" + contactNumber + '\'' +
                ", status='" + status + '\'' +
                ", createdAt=" + createdAt +
                '}';
    }
}
